### ISSUE TITLE
Consider, Decide and implement alternative labels for "approve" "reject", maybe?

### ISSUE THREAD

**Issue by campbellssource** [vegaprotocol/vegawallet-ui#116]
## The Chore

The desktop wallet ask you to "approve" transactions

<img width="756" alt="approve" src="https://user-images.githubusercontent.com/13255539/223717504-a370cd0f-cdfb-4d9d-a12d-0c0e3bcb9f65.png">

The CLI asks if you want to "send" Y/N.

<img width="618" alt="Screenshot 2023-03-08 at 12 33 54" src="https://user-images.githubusercontent.com/13255539/223717804-40a63a9c-b4f2-4cd9-a839-d4b753a38904.png">

Console says "approve" or "reject"
<img width="413" alt="Screenshot 2023-03-08 at 12 52 29" src="https://user-images.githubusercontent.com/13255539/223718060-dae4c738-8db4-4b85-b320-be7870f7a5c4.png">

Governance apps says "Confirm" (it might say other things in other places too

<img width="715" alt="Screenshot 2023-03-08 at 12 54 37" src="https://user-images.githubusercontent.com/13255539/223718521-1b32b28d-9f92-4691-8b7a-38344f03ab4f.png">

## Tasks

- [ ] Discuss this, decide if any change is needed
- [ ] Make changes to DT wallet and CLI as needed
- [ ] Raise tickets in other repos (console, token etc) as required

## Additional details / background info

I think the sign Vs send transaction is interesting and worth making it clear, in most cases you are both signing and sending the transaction.

### What lather wallets too (eth transactions so not 100% relevant)

<img width="358" alt="Screenshot 2023-03-08 at 12 01 35" src="https://user-images.githubusercontent.com/13255539/223718800-ea9bb48f-cb2b-4c11-a117-9fb7ad7cecac.png">

<img width="375" alt="Screenshot 2023-03-08 at 12 02 23" src="https://user-images.githubusercontent.com/13255539/223718880-95d6972a-6127-482c-825a-e6a6074fa0b3.png">

![IMG_2332](https://user-images.githubusercontent.com/13255539/223718909-756e5db4-0133-41a9-87cd-e1d19f503df3.PNG)

![IMG_2333](https://user-images.githubusercontent.com/13255539/223718922-90743464-caf8-48f3-996c-942330fb6f96.PNG)
