### ISSUE TITLE
Add tests for transaction log

### ISSUE THREAD

**Issue by dexturr** [vegaprotocol/vegawallet-ui#154]
## The Chore

In https://github.com/vegaprotocol/vegawallet-desktop/issues/488 we added a transaction log. Add tests for this.

## Tasks

- [ ] Identify ACs based on ticket
- [ ] Update specs (if applicable)
- [ ] Add mocked tests
- [ ] Consider adding desktop wallet tests if possible
