### ISSUE TITLE
Link to mainnet incident reports, feedback and known issues

### ISSUE THREAD

**Issue by pennyandrews** [vegaprotocol/vegawallet-ui#76]
## The Story

As a user 
I want to be able to find mainnet incident reports, known issues and to provide feedback 
So that I can understand current issues and their status, get a feel for how Vega responds to them and report my own issues that I find

Examples from Governance and Console:

![Image](https://github.com/vegaprotocol/vegawallet-ui/assets/47143694/a28a1473-0d04-46f0-b46d-47175cd77181)
![Image](https://github.com/vegaprotocol/vegawallet-ui/assets/47143694/379a349b-4f94-4d4f-9713-2b6ad3999eb4)

## Acceptance Criteria

- [ ] Mainnet status and incidents opens https://blog.vega.xyz/tagged/vega-incident-reports
- [ ] Share your feedback opens https://github.com/vegaprotocol/feedback/discussions
- [ ] The links are visually identifiable as external links an open in a new browser tab

## Tasks

- [ ] Add link in app (footer?) to 'Mainnet status & incidents' https://blog.vega.xyz/tagged/vega-incident-reports
- [ ] Add link in app (footer?) to 'Share your feedback' https://github.com/vegaprotocol/feedback/discussions

## Additional details / background info
(https://vegaprotocol.slack.com/archives/C02GZ0Q0NDC/p1673003925560669)
