### ISSUE TITLE
Light strategy for wallet app

### ISSUE THREAD

**Issue by ckpringle** [vegaprotocol/vegawallet-ui#94]
## Story

As a team
We want to set a direction for the wallet ui (desktop and browser) experience that brings it in-line with user expectations and what Vega needs
So that we know what we are aiming for and can create the tickets needed to improve the wallet's user experience  

## Tasks
- [ ] Understand what is 'different' when it comes to the Vega wallet (structure / approach / users)
- [ ] Review / compare competitor experiences against key journeys / interactions  - what experience will our wallet be benchmarked against by our users
- [ ] Collect user needs / insights from what we have from incentives / manual testing / community already
- [ ] Identify any gaps in our knowledge i.e. do we need further research of any kind
- [ ] Agree vision / goals for the wallet experience based on the above, and what that would mean to the UI (e.g. a sketch / set of key features)
